---
services:
  backend:
    container_name: backend
    build: ./backend
    ports: [23000:23000]
    environment:
      FRIGATE_CLIPS_PATH: ${FRIGATE_CLIPS_PATH}
      FRIGATE_DB_FILE_PATH: ${FRIGATE_DB_FILE_PATH}
    volumes:
      - ${FRIGATE_CLIPS_PATH}:${FRIGATE_CLIPS_PATH}
      - ${FRIGATE_DB_FILE_PATH}:${FRIGATE_DB_FILE_PATH}
    networks:
      llm_nvr:
        aliases: [backend]
  frontend:
    environment:
      BACKEND_URL_HOST: "backend"
      BACKEND_URL_PORT: "3000"
    container_name: frontend
    build: ./frontend
    ports: [23001:23001]
    depends_on: [backend]
    networks:
      llm_nvr:
        aliases: [frontend, ui]
    entrypoint: [node]
    command: [/usr/src/app/node_modules/vite/bin/vite.js, --host, "0.0.0.0", --port, "23001"]
networks:
  llm_nvr: {}
